// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma 7: this URL is used only by the CLI (migrate/introspect/db seed's
    // schema step), never by the generated PrismaClient at runtime. Uses the
    // session-mode pooler (DIRECT_URL) because migrations need session-level
    // features the transaction-mode pooler (DATABASE_URL) doesn't support.
    // The app's runtime connection is configured separately via a driver
    // adapter in lib/prisma.ts, pointed at DATABASE_URL.
    url: process.env["DIRECT_URL"],
  },
});
